sudo: false
os:
  - osx
  - linux
language: go
go:
  - 1.9.x
  - 1.10.x
  - master

install:
  - go get github.com/k0kubun/pp

script:
  - cd .build
  - CGO_LDFLAGS_ALLOW='-Wl.*' CGO_CFLAGS="-I$PWD" go build -v ..
  - cd ..

matrix:
  allow_failures:
    - go: master
  fast_finish: true
